# Generated by Django 5.1.3 on 2025-03-17 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_clientcrm_address_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='client_watsapp',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone_crm', to='clients.client'),
        ),
    ]
