# Generated by Django 5.1.3 on 2025-03-28 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_client_first_name_client_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='last_address_uuid',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='UUID последнего адреса'),
        ),
    ]
