services:
  db:
    image: postgres:15
    volumes:
      - postgres_data_water:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    expose:
      - "5432"
  web:
    container_name: water_web
    build: .
    command: >
      sh -c "
        python manage.py makemigrations --noinput &&
        python manage.py migrate --noinput &&
        python manage.py collectstatic --noinput &&
        gunicorn stations.wsgi:application --bind 0.0.0.0:8000 --workers 2
      "
    volumes:
      - .:/app
      - ./.env:/app/.env
      - static_volume_water:/var/www/static
      - media_volume_water:/var/www/media
    expose:
      - "8000"
    depends_on:
      - db
      - redis
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - web
      - db
    volumes:
      - static_volume_water:/var/www/static
      - media_volume_water:/var/www/media
      - ./nginx:/etc/nginx/conf.d
  redis:
    image: redis:alpine
    expose:
      - "6379"
  celery:
    build: .
#      context: .
#      dockerfile: Dockerfile.worker
    command: celery -A stations worker --loglevel=info
    volumes:
      - ./.env:/app/.env
    depends_on:
      - web
      - redis
  celery-beat:
    build: .
    command: celery -A stations beat --loglevel=info
    volumes:
      - ./.env:/app/.env
    depends_on:
      - web
      - redis
volumes:
  postgres_data_water:
  static_volume_water:
  media_volume_water:
