# Generated by Django 5.1.3 on 2025-04-13 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_cartitem_time_spot_alter_order_time_spot'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='payment_choice',
            field=models.CharField(default='cash', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_choice',
            field=models.CharField(default='cash', max_length=50),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order_uuid',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID в CRM'),
        ),
    ]
