# Generated by Django 5.1.3 on 2025-04-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_cartitem_payment_choice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='time_spot',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='time_end',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='time_start',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
