# Generated by Django 5.1.3 on 2025-04-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_remove_order_time_spot_order_delivery_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='uuid',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID в CRM'),
        ),
    ]
