# Generated by Django 5.1.3 on 2025-04-13 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_cartitem_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='uuid',
        ),
    ]
