# Generated by Django 5.1.3 on 2025-04-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_backend', '0006_alter_productblock_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='productblock',
            name='uuid',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID в CRM'),
        ),
    ]
