# Generated by Django 5.1.3 on 2025-04-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_backend', '0007_productblock_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='buttonmenu',
            name='special',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Нетиповое действие'),
        ),
    ]
