# Generated by Django 5.1.3 on 2025-03-18 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_phone_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientcrm',
            name='ur_off_city',
        ),
        migrations.RemoveField(
            model_name='clientcrm',
            name='ur_off_district',
        ),
        migrations.RemoveField(
            model_name='clientcrm',
            name='ur_off_house',
        ),
        migrations.RemoveField(
            model_name='clientcrm',
            name='ur_off_korp',
        ),
        migrations.RemoveField(
            model_name='clientcrm',
            name='ur_off_kv',
        ),
        migrations.RemoveField(
            model_name='clientcrm',
            name='ur_off_other',
        ),
        migrations.RemoveField(
            model_name='clientcrm',
            name='ur_off_region',
        ),
        migrations.RemoveField(
            model_name='clientcrm',
            name='ur_off_region_code',
        ),
        migrations.RemoveField(
            model_name='clientcrm',
            name='ur_off_settlement',
        ),
        migrations.RemoveField(
            model_name='clientcrm',
            name='ur_off_street',
        ),
        migrations.AddField(
            model_name='clientcrm',
            name='ur_off_address_city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientcrm',
            name='ur_off_address_district',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientcrm',
            name='ur_off_address_house',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clientcrm',
            name='ur_off_address_korp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clientcrm',
            name='ur_off_address_kv',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clientcrm',
            name='ur_off_address_other',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientcrm',
            name='ur_off_address_region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientcrm',
            name='ur_off_address_region_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clientcrm',
            name='ur_off_address_settlement',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientcrm',
            name='ur_off_address_street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
