# Generated by Django 5.1.3 on 2025-03-18 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_remove_clientcrm_ur_acсcount_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcrm',
            name='birthday',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientcrm',
            name='contract_1c_start_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
