# Generated by Django 5.1.3 on 2025-03-18 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_remove_address_crm_client_id_address_client_crm_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='client_crm_uuid',
        ),
        migrations.AddField(
            model_name='address',
            name='address_uuid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
