# Generated by Django 5.1.3 on 2025-03-18 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_remove_address_client_crm_uuid_address_address_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcrm',
            name='client_type',
            field=models.CharField(blank=True, choices=[('fiz', 'Физическое лицо'), ('ur', 'Юридическое лицо')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='clientcrm',
            name='ur_type',
            field=models.CharField(blank=True, choices=[('ip', 'ИП'), ('ooo', 'ООО'), ('zao', 'ЗАО'), ('ao', 'АО')], max_length=10, null=True),
        ),
    ]
