# Generated by Django 5.1.3 on 2025-03-20 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_alter_clientcrm_client_type_alter_clientcrm_ur_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcrm',
            name='ur_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phones_crm', to='crm.clientcrm'),
        ),
    ]
