# Generated by Django 5.1.3 on 2025-03-21 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_alter_clientcrm_ur_type_alter_phone_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='clientCrm',
        ),
        migrations.AddField(
            model_name='address',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='crm.clientcrm'),
        ),
        migrations.AddField(
            model_name='phone',
            name='client_uuid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
