# Generated by Django 5.1.3 on 2025-03-21 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_remove_address_clientcrm_address_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='phone',
            field=models.CharField(max_length=30),
        ),
    ]
