# Generated by Django 5.1.3 on 2025-03-21 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_remove_phone_client_remove_phone_client_watsapp_and_more'),
        ('crm', '0012_alter_phone_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneCRM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=30)),
                ('comment', models.TextField(blank=True, null=True)),
                ('notices', models.BooleanField(default=False)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('client_uuid', models.CharField(blank=True, max_length=255, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phones_crm', to='crm.clientcrm')),
                ('client_watsapp', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone_crm', to='clients.client')),
            ],
        ),
        migrations.DeleteModel(
            name='Phone',
        ),
    ]
