# Generated by Django 5.1.3 on 2025-03-21 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_alter_address_dom_alter_address_doorcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
