# Generated by Django 5.1.3 on 2025-03-21 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_alter_address_lat_alter_address_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='dom',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='address',
            name='doorcode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='entrance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='floor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='korp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='kv',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
