# Generated by Django 5.1.3 on 2025-03-22 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_alter_address_dom_alter_address_doorcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonecrm',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phones_crm', to='crm.clientcrm', unique=True),
        ),
        migrations.AlterField(
            model_name='phonecrm',
            name='phone',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
