# Generated by Django 5.1.3 on 2025-03-23 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_alter_phonecrm_client_alter_phonecrm_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonecrm',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phones_crm', to='crm.clientcrm'),
        ),
    ]
